### ISSUE TITLE
Loss of information in the mask

### ISSUE THREAD

**Issue by JaviCru** [Shondoit/lyne#1]
Hi, I have a question regarding the use of your script for preparing a dataset in Automatic 1111 with the "Use PNG alpha channel as loss weight" option.

When using this tool, a PNG image with transparency is generated, however, transparent pixels are removed (at least that's what I think). If the attention map were perfect, this wouldn't matter, but in many cases the attention map doesn't get it entirely right, and the transparent areas should come into play, at least not be removed, I don't know if I'm explaining myself correctly.

If I modify the 'target_range' argument of the 'scale_array' function and specify (10, 255) instead of (0, 255), the pixels outside the attention zone are preserved, and they would still come into play during training, albeit with much less weight than the attention zones.

Am I correct in this assumption?

**Comment by Shondoit** [comment]
Transparent pixels are not actually deleted, just made transparent. (The actual data is still there.)

Regarding the imprecise attention mask, SD is smart enough to fill in any gaps. It won't suddenly cut off parts just because it's transparent. Transparent in this case just means there's no focus there, so SD will fill in with what it already knows.

Also, be aware the weighting function in A1111 will rescale the map to a minimum of 0 and a mean of 1. (not max.)
This means that a transparency of 0-255 and 10-255 will be scaled practically the same.

What you _could_ do is play around with the `10%Rel.pos` value. If you change it to 100% (or 50%) the transparency will be less abrupt and more gradual.

**Comment by JaviCru** [comment]
> Transparent pixels are not actually deleted, just made transparent. (The actual data is still there.)

How can I be sure of this?

If I open the image in photoshop and go to Window -> Channels, I see the RGB, Red, Green and Blue channels, all with transparency applied. I don't see the original image and an Alpha channel where used as a mask.
On the other hand, if I convert the image with imagemagick a white background is applied.
How could I restore the 'transparent' pixels to confirm that the information is still there?

> What you could do is play around with the 10%Rel.pos value.

Thank you very much for this advice, I will test by adjusting this value.

**Comment by Shondoit** [comment]
I'm not sure if Photoshop has this ability, but in GIMP you can open the PNG, open Curves, choose Alpha for Channel, then lift everything to 255.

You could also possibly split into 4 channels (RGBA), fill alpha completely white and then recombine the channels.

Demonstration to show it's not lost when using this script:
![transparency_depth](https://user-images.githubusercontent.com/1111394/222119772-24a93ad2-2f9c-40ec-8348-e405eacec43a.png)

![transparency_removed](https://user-images.githubusercontent.com/1111394/222119810-14857dab-3320-488c-9267-67bf830cc7be.png)

**Comment by JaviCru** [comment]
Thank you very much, with GIMP it appears as you say, I will have to start migrating from photoshop to this software.

Thank you very much again.
